### ISSUE TITLE
Documentation defragmentation

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/style-guide#4]
We have three packages in this repo, and every package has a separate README with documentation. What do you think about moving all the documentation and instructions to the top-level README file?

We may create two sections, one for javascript and one for stylesheets, and common information for javascript (see #2) will need no duplication.

**Comment by viscoze** [comment]
@dzhlobo I thought the same way, and there is one thing: the way how to install react/js linters isn't the same. So looks like it's better to store this particular part of the instruction in separate readmes.

But what comes to the adding something... maybe the top level is more suitable. As you said we should divide it into JS and style sections

**Comment by dzhlobo** [comment]
@viscoze, I think it doesn't matter instructions are different, we still can have them in one README file. We may have a separate section for each linter.

It is pain to open multiple README files to read instructions.

**Comment by viscoze** [comment]
@dzhlobo ok, I got you bothering. Let's summarize it.

## Tension
It's pretty hard to find out how to install this linter, and it's just inconvenient to go to the whole readmes.

## Solution
Move the installation to the top readme.

Let's do it this way: we will create a separate PR with this changes and then check if it's ok and better that it is now

**Comment by viscoze** [comment]
@dzhlobo I've been thinking about having a separate section for each linter, and I don't think it's a good idea, because what comes to linters they have the same interface of configs (rules, plugins, etc.)
