### ISSUE TITLE
Distribute all packages with own version (and do we need monorepo?)

### ISSUE THREAD

**Issue by ezhlobo** [datarockets/style-guide#8]
Right now we publish all packages all together with the same version. But it looks very odd that when we want to update stylelint config, we also have to update eslint one. 

Another question: if we want to split all our packages into separate packages? It will give us easier maintenance but will also spread the one domain across multiple projects.

**Comment by atatarenko** [comment]
I'd break them because I don't feel they are under one domain. For example, I have js code linter setup on my project already, then I want only to add a linter for styles. I don't think about these two linters like about one domain.

**Comment by roman-dubrovsky** [comment]
@ezhlobo I don't really understand the current project structure but looks like it is already three different packages, isn't it?
